### ISSUE TITLE
Internal Server Error on sign in

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/app.co#753]
Intermittently, an Internet Server Error is thrown when authenticating with Blockstack.

The logs show this relates to Redis being OOM.

```
2019-12-12T10:32:03+00:00 app[heroku-redis]: source=REDIS addon=redis-elliptical-55978 sample#active-connections=2 sample#load-avg-1m=0.145 sample#load-avg-5m=0.12 sample#load-avg-15m=0.075 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664264kB sample#memory-free=13289120kB sample#memory-cached=747696kB sample#memory-redis=8915400bytes sample#hit-rate=0.89848 sample#evicted-keys=0
2019-12-12T10:32:36.805680+00:00 app[web.1]: Cache miss: /
2019-12-12T10:32:38.921212+00:00 app[web.1]: Error when saving page cache
2019-12-12T10:32:39.358609+00:00 app[web.1]: { ReplyError: OOM command not allowed when used memory > 'maxmemory'.
2019-12-12T10:32:39.358623+00:00 app[web.1]:     at parseError (/app/node_modules/redis-parser/lib/parser.js:193:12)
2019-12-12T10:32:39.358625+00:00 app[web.1]:     at parseType (/app/node_modules/redis-parser/lib/parser.js:303:14)
2019-12-12T10:32:39.358634+00:00 app[web.1]:   command: 'SET',
2019-12-12T10:32:39.358637+00:00 app[web.1]:   args:
```

@hstove Is this likely to be specific to the staging environment?

**Comment by markmhx** [comment]
@hstove Could we possibly up the amount of memory on staging to fix this?

**Comment by hstove** [comment]
We bumped up the size of the Redis cache. Let's keep an eye out for this again, but the size of the cache has been only 20% of the current max for the past day, so hopefully this will be fine. If we're hitting a lot of different cached pages (i.e. anything not maker or admin) the cache size will grow.
